Algoritmo "problemaSenha"

Var
   senhaCadastrada, cadastrarSenha : inteiro

Inicio
      escreval("Crie uma senha:")
      leia(cadastrarSenha)
      
      enquanto senhaCadastrada <> cadastrarSenha faca
               escreval("Senha invalida! Digite a senha de cadastro:")
               leia(senhaCadastrada)
      fimenquanto
      
      escreval("Acesso permitido!")

Fimalgoritmo