Algoritmo "para"

Var
   quantidade, numero, soma : inteiro
   
Inicio

      soma <- 0
      escreval("Digite a quantidade de numero que deseja:")
      leia(quantidade)
      
      para numero de 1 ate quantidade faca
           escreval("Digite os numeros desejados")
           leia(numero)

           soma <- soma + numero
      fimpara
      
      escreval(soma)

Fimalgoritmo