Algoritmo "vetores"

Var
   n, i : inteiro
   vet : vetor[0..9] de real

Inicio
      escreval("Digite a quantidade dados que serao inserido: ")
      leia(n)
      
      para i de 0 ate n -1 faca
           escreval("Digite os dados:")
           leia(vet[i])
      fimpara
      escreval()
      escreval("Numeros digitados")
      
      para i de 0 ate n -1 faca
           escreval(vet[i])
      fimpara

Fimalgoritmo