Algoritmo "entradaDados"

Var
   idade : inteiro
   salario01, salario02 : real
   nome : caractere
   
Inicio
      escreval("Digite o seu nome: ")
      leia(nome)
      escreval("Digite a sua idade: ")
      leia(idade)
      escreval("Digite quanto voce ganhou nos dois ultimos meses: ")
      leia(salario01)
      leia(salario02)
      
      escreval("Dados Digitados: ")
      escreval("Nome = ", nome)

Fimalgoritmo